# Generated by Django 3.2.3 on 2024-10-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241028_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationstoragedist',
            options={'ordering': ('distance',)},
        ),
        migrations.AlterModelOptions(
            name='storagedistance',
            options={'ordering': ('distance',)},
        ),
    ]
