# Generated by Django 3.2.3 on 2024-10-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241028_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagedistance',
            old_name='storage_neighbour',
            new_name='neighbour_storage',
        ),
    ]
