# Generated by Django 3.2.3 on 2024-10-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_storage_neighbour_storagedistance_neighbour_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='biowaste_max',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Предел биоотходов'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='glass_max',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Предел стекла'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='plastic_max',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Предел пластика'),
        ),
    ]
