# Generated by Django 3.2.3 on 2024-10-31 10:12

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_storagedistance_check_storage_neighbour_unique_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storagedistance',
            constraint=models.CheckConstraint(check=models.Q(('storage', django.db.models.expressions.F('neighbour_storage')), _negated=True), name='check_create_self_as_neighbour'),
        ),
    ]
