# Generated by Django 3.2.3 on 2024-10-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_storagedistance_check_create_self_as_neighbour'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storagedistance',
            constraint=models.UniqueConstraint(fields=('storage', 'neighbour_storage'), name='check_storage_neighbour_unique_constraint'),
        ),
    ]
