# Generated by Django 3.2.3 on 2024-11-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20241101_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='storage',
            new_name='storages',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='nearby_storage',
        ),
        migrations.AddField(
            model_name='storage',
            name='nearby_storages',
            field=models.ManyToManyField(related_name='_core_storage_nearby_storages_+', through='core.StorageDistance', to='core.Storage'),
        ),
        migrations.AlterField(
            model_name='organizationstoragedist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Организация'),
        ),
    ]
