# Generated by Django 3.2.3 on 2024-11-05 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20241104_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',), 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='organizationstoragedist',
            options={'ordering': ('distance',), 'verbose_name': 'Организация и хранилище', 'verbose_name_plural': 'Организации и хранилища'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ('name',), 'verbose_name': 'Хранилище', 'verbose_name_plural': 'Хранилища'},
        ),
        migrations.AlterModelOptions(
            name='storagedistance',
            options={'ordering': ('distance',), 'verbose_name': 'Хранилище-сосед', 'verbose_name_plural': 'Хранилища-соседи'},
        ),
        migrations.AlterModelOptions(
            name='waste',
            options={'ordering': ('id',), 'verbose_name': 'Отходы', 'verbose_name_plural': 'Отходы'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='waste',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waste', to='core.waste', verbose_name='id модели отходов'),
        ),
        migrations.AlterField(
            model_name='organizationstoragedist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='core.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='waste',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.waste', verbose_name='id модели отходов'),
        ),
    ]
